### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [fernandobritto/central-cities#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by fernandobritto** [comment]
Hi, thank you very much for your interest. I added the MIT license to the project. Please create what you need. Can make changes and create a pull request. In addition, you can also add instructions on how TS and JS people can use it will be cool. Thank you for contributing.

**Comment by geopic** [comment]
Great stuff, I'll start on it today 👍
